name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d85c6cca4b737c44cfff7f0b4dc0c12da98d52479e1c4d810cbeb65886ef3010"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
