name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "046cd42b857c954df2ac1ed8a3f3f5d9a0aac6f24f8c02d4096f2e5465dcd604"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
