name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d0a7d6ab923e61ad008c88d09fe5d25f194a9f2e953d9c67342c9f96e67bab3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
