name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72f21fa2f5cfc4aa35ef615711de36a2b89e14b3116a2956b9165a6f0a51d91c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
