name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2372b1a1eec13143b6a3bd956cbeaeab18e88946b72641cb5d2a951a41fb43c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
