name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a159b0bbcc9150bd4f7be48b7950ecf4d7b4d018aa9cb5b7414f1ccabc853191"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
