name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f3d2c927af65d0ce8ddf42ad48f0a9847aebad2ac2d8470104a381e52cffd73"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
