name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2c2e368f630dcbe5ae503a97d0dfbe48961031c74b7a07063af6b13dce5b6f4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
