name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09cc930dbff2513c316d76361b4335089fc0d6b779505e8d2c54e113693fe98c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
