name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9115aa2255af4688834b0b605b1ed00d92d4a3c9c1b325f54520532e16f41abc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
