name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c81648bdf64e5bf15cd46125166c233abc576bd60c26bc045eaecf239d206bdc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
