name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2aa08fa4083f868df18e1db1d5e90791c3927decce343eab53867fac8541d73f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
