name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e17bdd7af55da1ad0e8fc33b91fcdd818a80e7a99dd87ca5cc6435ad4fa5088"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
