name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16bec1a0d8df2c4f59782599c287c4ab92a11647f463fd33fa34a0ba9f5a1467"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
