name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecf5b0103d36c86db8ba222babf58e27e708fe5fb0acdd39c3546ebe1f90e36d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
