name = "ğ“•ğ“»ğ“®ğ“ªğ“´ğ”‚Craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86242b661c554d585367282adabf59dc9c6fcdd9380cea6296665792006a8c47"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
